### ISSUE TITLE
Broken link to existing claim schemas

### ISSUE THREAD

**Issue by joshsny** [0xPolygonID/tutorials#1]
Great resource, thanks so much for putting it all together.

Just wanted to report that there is a broken link to view existing claim schemas on the following page of the [documentation](https://0xpolygonid.github.io/tutorials/getting-started/claim/claim-schema/). The link has text `existing claim schemas`.

Tried to find the correct link but I wasn't able to see the schemas in any of your public repositories.

**Comment by enricobottazzi** [comment]
Hi @joshsny, the repo is now public so the link should not be broken anymore.

Thanks for the patience and would appreciate any feedback if you are diving into the tutorials
