### ISSUE TITLE
Invalid polygonId flutter sdk link

### ISSUE THREAD

**Issue by marija-mijailovic** [0xPolygonID/tutorials#13]
The link in the [tutorial](https://github.com/0xPolygonID/tutorials/blob/380a1b0ebb2c06bf28e987b4c61d03d424d01537/mkdocs/docs/wallet/wallet-sdk/polygonid-sdk/example-app.md) for [polygonid-sdk-repository](https://github.com/iden3/polygonid-flutter-sdk) is not open for public or is invalid.

**Comment by otto-mora** [comment]
Hello @marija-mijailovic , please give us a couple of weeks  Stay tuned for late February.  ;-).

**Comment by otto-mora** [comment]
Hello @marija-mijailovic please try again: https://github.com/iden3/polygonid-flutter-sdk :-)
